### ISSUE TITLE
Does not automatically reconnect

### ISSUE THREAD

**Issue by keeth** [tonyvanriet/clj-slack-client#1]
Seemingly at random (maybe once a day or so) I notice my bot will print

```
reconnecting...
```

to the log but never actually reconnect.

I'll probably turn on netty debug logging or something to see what's going on, just wanted to raise it as an issue in case there's anything I can try.

**Comment by tonyvanriet** [comment]
The client tries to reconnect if a pong is not received for over 10 seconds, similar to the references Slack client. The problem was that, in this case, the reconnect was running on the ping-loop thread, and reconnect kills the ping-loop thread to clean up, so the reconnect could not complete.

Thanks again @keeth

**Comment by keeth** [comment]
Awesome! Thanks so much.
